version: '3'
services:
  integration_testing:
    volumes:
      - ./container/calc/app:/var/integration_testing/container/calc/app
      - ./container/display/app:/var/integration_testing/container/display/app
    command: [pytest, tests/test_display_and_calc.py]

